export const ErrorCodes = {
  VALIDATION_ERROR: 'GOAL_VALIDATION_ERROR',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FORBIDDEN: 'OWNERSHIP_FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DEV_AUTH_REQUIRED: 'DEV_AUTH_REQUIRED',
  AUTH_PROVIDER_REQUIRED: 'AUTH_PROVIDER_REQUIRED',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL_ERROR',
  GOAL_NAME_REQUIRED: 'GOAL_NAME_REQUIRED',
  GOAL_DEADLINE_IN_PAST: 'GOAL_DEADLINE_IN_PAST',
  GOAL_TARGET_AMOUNT_INVALID: 'GOAL_TARGET_AMOUNT_INVALID',
  GOAL_CURRENT_AMOUNT_EXCEEDS_TARGET: 'GOAL_CURRENT_AMOUNT_EXCEEDS_TARGET',
  GOAL_CURRENCY_REQUIRED: 'GOAL_CURRENCY_REQUIRED',
  GOAL_CUSTOM_CATEGORY_REQUIRED: 'GOAL_CUSTOM_CATEGORY_REQUIRED',
  GOAL_MILESTONE_INVALID: 'GOAL_MILESTONE_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
